
auth.token=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

defaults.org=drivest
defaults.project=react-native

defaults.url=https://sentry.io/
